---

env:
  global:
    - VAGRANT_VERSION='2.2.18'
  jobs:
    - PLATFORM=debian7
    - PLATFORM=debian8
    - PLATFORM=debian9
    - PLATFORM=debian10
    - PLATFORM=debian11
    - PLATFORM=ubuntu16.04
    - PLATFORM=ubuntu18.04

os:
  - linux
dist: focal

language: python
python:
  - 3.8

services:
  - docker

before_install:
  - sudo apt-get -q update
  - sudo wget -nv https://releases.hashicorp.com/vagrant/${VAGRANT_VERSION}/vagrant_${VAGRANT_VERSION}_x86_64.deb

install:
  - sudo dpkg -i vagrant_${VAGRANT_VERSION}_x86_64.deb
  - sudo pip install ansible

script:
  - vagrant status
  - vagrant up $PLATFORM
  - vagrant status
